# -*- coding: utf-8 -*-
"""amazon_review_keyword_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3uuWbOjBYxBps2cXq32zPzKgl8nuE_Z
"""

import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
from nltk.util import ngrams

df = pd.read_csv('glassdoor_cleaned_with_text.csv')

df.info()

"""Create a column of only "cleaned text"
"""

df["cleaned_text"] = (
    df["pros_cleaned"].fillna("") + " " +
    df["cons_cleaned"].fillna("") + " " +
    df["advice_cleaned"].fillna("") + " " +
    df["summary_cleaned"].fillna("") + " "
    )
df[["pros_cleaned", "cons_cleaned", "cleaned_text"]].head()

"""record top 5 words that have been repeated again and again"""

all_words = ' '.join(df['cleaned_text']).split()
word_counts = Counter(all_words)

print(word_counts.most_common(5))

"""Creating a visual for top 10 keywords


"""

most_common = word_counts.most_common(10)
words, counts = zip(*most_common)

plt.bar(words, counts)
plt.title("Top 10 Keywords (Unigrams)")
plt.xticks(rotation = 45)
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""get rid of useless keywords:"""

stop_keywords = ['get','amazon','job']
filtered_words = [ word for word in all_words if word not in stop_keywords]
filtered_counts = Counter(filtered_words)

most_common = filtered_counts.most_common(10)
words, counts = zip(*most_common)

plt.bar(words, counts)
plt.title("Top 10 Keywords (Unigrams)")
plt.xticks(rotation = 45)
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""Great, looks much better"""