# -*- coding: utf-8 -*-
"""amazon_review_data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKE-1aOudYA82imE6l2ue2Ag8Vy75UcI
"""

import pandas as pd

df = pd.read_csv("glassdoor_cleaned.csv")

df.shape

df.head()

df.info()

df.duplicated().sum()

df[['review_pros','review_cons', 'review_advice']].isnull().sum()

df.sample(5)

df.to_csv("glassdoor_cleaned_final.csv", index=False)
