# -*- coding: utf-8 -*-
"""youtube_text_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GecmQZGlCISTPhxbBPdIdO4XpChLdFvm
"""

import pandas as pd
import nltk
import string
from nltk.corpus import stopwords

nltk.download('stopwords')

data = pd.read_csv("youtube_reviews.csv")

print(data.info())

def clean_text(text):
  if pd.isnull(text):
    return ""
  tokens = text.lower().translate(str.maketrans('','', string.punctuation)).split()
  return ' '.join([word for word in tokens if word not in stopwords.words('english')])

data['transcript_cleaned'] = data['Transcript/Transcript Link'].apply(clean_text)

print(data.head())

data.to_csv("youtube_reviews_cleaned.csv", index = False)
