# -*- coding: utf-8 -*-
"""youtube_keyword_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOMcRvoYKjwr-oc_KQ6oh1zGbxYiO7L6
"""

import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
from nltk.util import ngrams

df = pd.read_csv("youtube_reviews_cleaned.csv")

df.info()

all_words = ' '.join(df['transcript_cleaned']).split()
word_counts = Counter(all_words)

print(word_counts.most_common(5))

most_common = word_counts.most_common(10)
words, counts = zip(*most_common)

plt.bar(words, counts)
plt.title("Top 10 Keywords (Unigrams)")
plt.xticks(rotation = 45)
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

stop_keywords = ['get','im','got','going','like','isnt']
filtered_words = [ word for word in all_words if word not in stop_keywords]
filtered_counts = Counter(filtered_words)

most_common = filtered_counts.most_common(10)
words, counts = zip(*most_common)

plt.bar(words, counts)
plt.title("Top 10 Keywords (Unigrams)")
plt.xticks(rotation = 45)
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()
